// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb-gqAITOP2zFadIGddZNa6GGf9vgCFfw',
    appId: '1:211504040174:web:d2a4823b32282595d20bff',
    messagingSenderId: '211504040174',
    projectId: 'pantrypal-c55f0',
    authDomain: 'pantrypal-c55f0.firebaseapp.com',
    storageBucket: 'pantrypal-c55f0.firebasestorage.app',
    measurementId: 'G-K0JEPB79GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7k5LMxU8UPhN6rl_IGD2YchRlH42T7g0',
    appId: '1:211504040174:android:55301854b27de56fd20bff',
    messagingSenderId: '211504040174',
    projectId: 'pantrypal-c55f0',
    storageBucket: 'pantrypal-c55f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXKcGriJwz4olmNergbHx-rZ3AwG2aWWw',
    appId: '1:211504040174:ios:f9a12adc8d191a49d20bff',
    messagingSenderId: '211504040174',
    projectId: 'pantrypal-c55f0',
    storageBucket: 'pantrypal-c55f0.firebasestorage.app',
    iosBundleId: 'com.example.pantrypalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXKcGriJwz4olmNergbHx-rZ3AwG2aWWw',
    appId: '1:211504040174:ios:50c027ab45f34044d20bff',
    messagingSenderId: '211504040174',
    projectId: 'pantrypal-c55f0',
    storageBucket: 'pantrypal-c55f0.firebasestorage.app',
    iosBundleId: 'com.pantrypal.pantrypalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb-gqAITOP2zFadIGddZNa6GGf9vgCFfw',
    appId: '1:211504040174:web:f721af72d22f047bd20bff',
    messagingSenderId: '211504040174',
    projectId: 'pantrypal-c55f0',
    authDomain: 'pantrypal-c55f0.firebaseapp.com',
    storageBucket: 'pantrypal-c55f0.firebasestorage.app',
    measurementId: 'G-D983YE0X9T',
  );
}
